name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Prepare deploy directory on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: sudo mkdir -p /tmp/deploy && sudo chown -R ubuntu:ubuntu /tmp/deploy

    - name: Upload dist via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        source: "dist"
        target: "/tmp/deploy"
        strip_components: 1

    - name: Move to web root and cleanup
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          sudo rm -rf /var/www/boomeroff/*
          sudo cp -a /tmp/deploy/. /var/www/boomeroff/
          sudo chown -R www-data:www-data /var/www/boomeroff/
          sudo rm -rf /tmp/deploy
